### ISSUE TITLE
Fix the ASDC Plugin

### ISSUE THREAD

**Issue by eholum** [ChandraCXC/iris-dev#87]
As far as I can tell it broke between commits

29b547b and f4875ba

That is, it worked in 29b547b and is broken in f4875ba

Issue with a runtime dependency in the commons-codec which is not entirely clear to me:

Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.decodeBase64(Ljava/lang/String;)[B
    at org.asdc.iris.plugin.asdcirisplugin.CatalogTree.getCatalogTree(CatalogTree.java:61)
    at org.asdc.iris.plugin.asdcirisplugin.PluginMainFormCal.<init>(PluginMainFormCal.java:263)
    at org.asdc.iris.plugin.asdcirisplugin.AsdcComponent$AsdcMenuItem.onClick(AsdcComponent.java:120)
    at cfa.vo.iris.desktop.DesktopButton$1$1.run(DesktopButton.java:56)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by olaurino** [comment]
did you use git bisect for figuring this out? If you did it might be worth
documenting the procedure in UDF.

On Wed, May 25, 2016 at 11:07 AM, Erik Holum notifications@github.com
wrote:

> As far as I can tell it broke between commits
> 
> 29b547b and f4875ba
> 
> That is, it worked in 29b547b and is broken in f4875ba
> 
> Issue with a runtime dependency in the commons-codec which is not entirely
> clear to me:
> 
> Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError:
> org.apache.commons.codec.binary.Base64.decodeBase64(Ljava/lang/String;)[B
> at
> org.asdc.iris.plugin.asdcirisplugin.CatalogTree.getCatalogTree(CatalogTree.java:61)
> at
> org.asdc.iris.plugin.asdcirisplugin.PluginMainFormCal.(PluginMainFormCal.java:263)
> at
> org.asdc.iris.plugin.asdcirisplugin.AsdcComponent$AsdcMenuItem.onClick(AsdcComponent.java:120)
> at cfa.vo.iris.desktop.DesktopButton$1$1.run(DesktopButton.java:56)
> at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
> at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
> at java.awt.EventQueue.access$300(EventQueue.java:103)
> at java.awt.EventQueue$3.run(EventQueue.java:706)
> at java.awt.EventQueue$3.run(EventQueue.java:704)
> at java.security.AccessController.doPrivileged(Native Method)
> at
> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
> at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
> at
> java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
> at
> java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
> at
> java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
> at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ChandraCXC/iris-dev/issues/87

## 

Omar Laurino
Smithsonian Astrophysical Observatory
Harvard-Smithsonian Center for Astrophysics
100 Acorn Park Dr. R-377 MS-81
02140 Cambridge, MA
(617) 495-7227

**Comment by eholum** [comment]
I didn't do that much with it other than to try and identify the last good state/earliest bad state.

**Comment by olaurino** [comment]
which is what git bisect is for :D 

you write a script that allows you to reproduce an issue or skip unbuildable commits: then you let git bisect traverse the commit graph searching for the last good state/earlier bad state, while you do something else.
